### ISSUE TITLE
Documentation on blog is misleading

### ISSUE THREAD

**Issue by bozicm** [lucisgit/moodle-jmeter-script-generator#5]
Documentation on http://www.open.ac.uk/blogs/XHProf/?page_id=64 is wrong about plugin installation path ([moodle_dir]/admin/report/loadtesting) whereas README gives the right installation path ([moodle_dir/report/loadtesting).

**Comment by kabalin** [comment]
Yeah, it not updated by its author. The link to the blog post is provided for general reference only (i.e. to show where the code came from and give people some idea on how to use it). In addition we have pre_2.2 branch for which [moodle_dir]/admin/report/loadtesting is the correct path.
